version: '3'
services:
    mongo:
        image: "mongo"
        ports:
            - "27017:27017"
    client:
        image: client
        build: ./services/client
        ports:
          - '4200:4200' # Port mapping
        command: >
          bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    db-accessor:
        image: db-accessor
        build: ./services/db-accessor
        command: node db-accessor.js
        ports:
            - "8002:8002"
        depends_on:
            - "mongo"
    backend:
        image: backend
        build: ./services/backend
        ports:
          - '3001:3001' # Port mapping
        command: >
          bash -c "nest start"